### ISSUE TITLE
openapi.yaml is not in sync with actual JSON structure

### ISSUE THREAD

**Issue by shred** [moov-io/fed#225]
The `openapi.yaml` specs define these properties:

```yaml
    ACHDictionary:
      description: Search results containing ACHDictionary of Participants
      properties:
        ACHParticipants:
```

```yaml
    WIREDictionary:
      description: Search results containing WIREDictionary of Participants
      properties:
        WIREParticipants:
```

These properties are starting with upper case letters.

However, the service actually returns fields named `achParticipants` and `wireParticipants` (starting lower case). This is breaking clients that are automatically generated from the `openapi.yaml` file.

Please update the `openapi.yaml` file. Thank you!
